import type { Task, Volunteer } from './types';

export const initialVolunteers: Volunteer[] = [
  {
    id: 1,
    name: 'John Doe',
    level: 'beginner',
    tokens: 0,
    completedTasks: [],
  },
  {
    id: 2,
    name: 'Jane Smith',
    level: 'beginner',
    tokens: 10,
    completedTasks: [101],
  },
  {
    id: 3,
    name: 'Peter Jones',
    level: 'intermediate',
    tokens: 55,
    completedTasks: [102, 103, 104],
  },
];

export const initialTasks: Task[] = [
  {
    id: 1,
    title: 'Clean Local Park',
    description: 'Spend 2 hours picking up trash at the main city park.',
    difficulty: 'easy',
    tokens: 10,
    status: 'open',
    assignedTo: null,
    createdBy: 'organizer',
  },
  {
    id: 2,
    title: 'Community Garden Weeding',
    description: 'Help weed the vegetable beds for 1 hour.',
    difficulty: 'easy',
    tokens: 10,
    status: 'in_progress',
    assignedTo: 2,
    createdBy: 'organizer',
  },
  {
    id: 3,
    title: 'Organize Library Books',
    description: 'Sort and shelve returned books at the public library.',
    difficulty: 'intermediate',
    tokens: 25,
    status: 'open',
    assignedTo: null,
    createdBy: 'organizer',
  },
  {
    id: 4,
    title: 'Build a Birdhouse',
    description: 'Construct a birdhouse for the community nature trail.',
    difficulty: 'intermediate',
    tokens: 25,
    status: 'completed',
    assignedTo: 3,
    completedBy: 3,
    createdBy: 'organizer',
  },
  {
    id: 5,
    title: 'Lead a Workshop',
    description: 'Lead a 1-hour workshop on a skill you have.',
    difficulty: 'difficult',
    tokens: 50,
    status: 'open',
    assignedTo: null,
    createdBy: 'organizer',
  },
  {
    id: 6,
    title: 'Soup Kitchen Service',
    description: 'Serve meals for 3 hours at the downtown soup kitchen.',
    difficulty: 'intermediate',
    tokens: 25,
    status: 'verified',
    assignedTo: 3,
    completedBy: 3,
    createdBy: 'organizer',
  },
];
